@startuml
actor AccountAdmin as AA
participant SAP as "<external>\nSAP" #96d0ff
AA -> SAP: eröffne Konto

participant "SAP-Adapter" as SA
SAP -> SA : send\naccount\ndetails
SAP -> SA : authorize

participant "Account\nDomain\nAggregate" as ADA

SA -> UserDB: userExisting?
SA -> ADA: get accountID
ADA -> ADA: activate
ADA -> Reporting: include\nin monthly\nreport


@enduml